@extends('layout')
@section('titulo')
@endsection
@section('header')
@endsection
@section('conteudo')
IDG:{{$generos->id_genero}}<br>
Designação:{{$generos->designacao}}<br>
Observações:{{$generos->observacoes}}
@endsection